version: '3'

services:
  app:
    build: .
    image: sigmappl
    container_name: sigmappl
    ports:
      - "8000:8000"  # Port mapping
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/sigmappl  
    volumes:
      - .:/var/www/sigmappl
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
       - sigmappl
  webserver:
    image: nginx:latest
    container_name: nginxlaraveldocker
    restart: unless-stopped
    tty: true
    ports:
     - "2022:80"
    volumes:
      - .:/var/www/sigmappl
      - ./storage/:/etc/nginx/conf.d/
    networks:
      - sigmappl

  db:
    image: mysql:latest 
    container_name: dblaraverdocker
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    tty: true
    ports:
      - "20222:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - sigmappl

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmalaraveldocker
    links:
      - db
    restart: always
    ports:
      - 7000:80 
    networks:
      - sigmappl

networks:
  sigmappl:
    driver: bridge

volumes:
  lbdata:
    driver: local
